### ISSUE TITLE
gw2pvo-1.5.3.tar.gz

### ISSUE THREAD

**Issue by isbrodie1** [jakezp/gw2pvo-alt#1]
Thanks for the work on this, I'm currently getting this issue when i changed from gw2pvo to gw2pvo-alt.

:\Users\xxxxx>gw2pvo --gw-station-id xxxxxxxxxxxxxxxxxx --gw-account xxxxxxxxxxxxxxxx --gw-password xxxxxxxxxxxxx --pvo-system-id xxxxxxxxx --pvo-api-key xxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python39\Scripts\gw2pvo-script.py", line 33, in <module>
    sys.exit(load_entry_point('gw2pvo==1.5.3', 'console_scripts', 'gw2pvo')())
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python39\Scripts\gw2pvo-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\xxxxx\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\xxxxx\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\xxxxx\appdata\local\programs\python\python39\lib\site-packages\gw2pvo\__main__.py", line 22, in <module>
    from gw2pvo import mqtt
  File "c:\users\xxxxxx\appdata\local\programs\python\python39\lib\site-packages\gw2pvo\mqtt.py", line 6, in <module>
    import paho.mqtt.client as mqtt
ModuleNotFoundError: No module named 'paho'

Any ideas what the blocker could be here?

**Comment by jakezp** [comment]
I'm not really actively working on this, since I've got it at a point where it's working fine for me. I've moved away from using data from the SEMS portal. I collect the data directly from the inverter and dump it to MQTT. 

Functionality for connecting to SEMS portal was left in place, but may not be working as expected as I did not test it after making all the changes. 

The error message you receive is because you're missing paho-mqtt. You can install it using  `pip install paho-mqtt`.

Install paho-mqtt and give it a bash to see if it's working for you. 

Keep in mind, I've created this for my own use and as per the disclaimer in the README.md, it will probably not work for others without tweaks / modifications. You can also try https://github.com/markruys/gw2pvo, if you're only interested in using data from the SEMS portal.

**Comment by isbrodie1** [comment]
Thanks for your help, I managed to get your script working by installing
paho-mqtt and now PVoutput is taking consumption and generation from SEMS
to PVoutput.

Cheers

**Comment by isbrodie1** [comment]
Thanks for your help, I managed to get your script working by installing paho-mqtt and now PVoutput is taking consumption and generation from SEMS to PVoutput.

Cheers
